### PR TITLE
Nice lab2. (Didn't understand anything)

### PR DESCRIPTION
**Pull request by ivankrut856**

### CODE REVIEW

**Review by krinkin — CHANGES_REQUESTED** [review]
Please, elaborate what exactly you don't understand? What should be discussed during the practice?

**Comment by ivankrut856** [comment]
> Please, elaborate what exactly you don't understand? What should be discussed during the practice?

Let us leave it to theoretical discussion and accept my PR :) The Lab is just confusing and counterintuitive.

**Comment by krinkin** [comment]
OK, I will accept this pull request, but I started to feel that you are cheating me and this solution has been written off from somebody. Good luck

**Review by krinkin — APPROVED** [review]

**Comment by ivankrut856** [comment]
> OK, I will accept this pull request, but I started to feel that you are cheating me and this solution has been written off from somebody. Good luck

Wow-wow. Definitely not. Ok, let me explain. I have my own understanding of the concept of virtual memory and stuff, but it kinda reveals broken when I try to implement it, then I have to rewrite the solution with support of the environment's feedback rather than my understanding. That kind of things I call counterintuitive. That's all

**Pull request merged**
